name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -migrate-state --backend-config=default.conf || terraform init --backend-config=default.conf -reconfigure || terraform init --backend-config=default.conf

      - name: Terraform Validate
        run: terraform validate

  create-pr-to-main:
    name: "Create PR to Main"
    needs: build-and-test # Garante que o PR só será aberto se o build e os testes passarem
    runs-on: ubuntu-latest
    # Executa este job SOMENTE quando houver um push/merge na branch develop
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    permissions:
      pull-requests: write # Permissão necessária para o bot do GitHub abrir o PR
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para obter o histórico da branch main

      - name: Create Pull Request via GitHub CLI
        env:
          GH_TOKEN: ${{  secrets.GITHUB_TOKEN  }}
        run: |
          git fetch origin main

  terraform:
    name: "Terraform Deploy"
    needs: build-and-test # Garante que o deploy só rode se os testes passarem
    runs-on: ubuntu-latest
    # Executa este job SOMENTE quando houver um push na branch main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: prod

    permissions:
      id-token: write # Necessário para interagir com o OIDC da AWS
      contents: read

    defaults:
      run:
        # Define o diretório onde os comandos do Terraform serão executados
        working-directory: envs/prod

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Credenciais da AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{  secrets.AWS_ACCOUNT_ID  }}:role/GitHubActionMinhoteca
          aws-region: ${{  secrets.AWS_REGION  }}
          role-session-name: GitHubActionsTerraformDeploy
          disable-retry: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -migrate-state --backend-config=default.conf || terraform init --backend-config=default.conf -reconfigure || terraform init --backend-config=default.conf

      - name: Terraform Plan
        env:
          TF_VAR_domain_name: ${{ vars.domain_name }}
          TF_VAR_dnssec_name: ${{ vars.dnssec_name }}
          TF_VAR_enable_dnssec: ${{ vars.enable_dnssec }}
          TF_VAR_kms_log_description: ${{ vars.kms_log_description }}
          TF_VAR_kms_verify_alias_name: ${{ vars.kms_verify_alias_name }}
          TF_VAR_kms_verify_description: ${{ vars.kms_verify_description }}
          TF_VAR_kms_log_alias_name: ${{ vars.kms_log_alias_name }}
          TF_VAR_bucket_frontend_allowed_origins: ${{ vars.bucket_frontend_allowed_origins }}
          TF_VAR_bucket_frontend_name: ${{ vars.bucket_frontend_name }}
          TF_VAR_bucket_arquivos_allowed_origins: ${{ vars.bucket_arquivos_allowed_origins }}
          TF_VAR_bucket_arquivos_name: ${{ vars.bucket_arquivos_name }}
          TF_VAR_arquivos_path_rewrite: ${{ vars.arquivos_path_rewrite }}
          TF_VAR_bucket_cdn_log: ${{ vars.bucket_cdn_log }}
          TF_VAR_spa_route_rewrite: ${{ vars.spa_route_rewrite }}
          TF_VAR_arquivos_cache_policy_name: ${{ vars.arquivos_cache_policy_name }}
          TF_VAR_arquivos_cache_policy_default_ttl: ${{ vars.arquivos_cache_policy_default_ttl }}
          TF_Var_arquivos_cache_policy_max_ttl: ${{ vars.arquivos_cache_policy_max_ttl }}
          TF_Var_arquivos_cache_policy_min_ttl: ${{ vars.arquivos_cache_policy_min_ttl }}
          TF_VAR_log_retention_in_days: ${{ vars.log_retention_in_days }}
          TF_VAR_log_route53_group_name: ${{ vars.log_route53_group_name }}
          TF_VAR_domain_log_policy: ${{ vars.domain_log_policy }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        # O auto-approve é essencial em ambientes de CI/CD pois não há interação humana
        env:
          TF_VAR_domain_name: ${{ vars.domain_name }}
          TF_VAR_dnssec_name: ${{ vars.dnssec_name }}
          TF_VAR_enable_dnssec: ${{ vars.enable_dnssec }}
          TF_VAR_kms_log_description: ${{ vars.kms_log_description }}
          TF_VAR_kms_verify_alias_name: ${{ vars.kms_verify_alias_name }}
          TF_VAR_kms_verify_description: ${{ vars.kms_verify_description }}
          TF_VAR_kms_log_alias_name: ${{ vars.kms_log_alias_name }}
          TF_VAR_bucket_frontend_allowed_origins: ${{ vars.bucket_frontend_allowed_origins }}
          TF_VAR_bucket_frontend_name: ${{ vars.bucket_frontend_name }}
          TF_VAR_bucket_arquivos_allowed_origins: ${{ vars.bucket_arquivos_allowed_origins }}
          TF_VAR_bucket_arquivos_name: ${{ vars.bucket_arquivos_name }}
          TF_VAR_arquivos_path_rewrite: ${{ vars.arquivos_path_rewrite }}
          TF_VAR_spa_route_rewrite: ${{ vars.spa_route_rewrite }}
          TF_VAR_bucket_cdn_log: ${{ vars.bucket_cdn_log }}
          TF_VAR_arquivos_cache_policy_name: ${{ vars.arquivos_cache_policy_name }}
          TF_VAR_arquivos_cache_policy_default_ttl: ${{ vars.arquivos_cache_policy_default_ttl }}
          TF_Var_arquivos_cache_policy_max_ttl: ${{ vars.arquivos_cache_policy_max_ttl }}
          TF_Var_arquivos_cache_policy_min_ttl: ${{ vars.arquivos_cache_policy_min_ttl }}
          TF_VAR_log_retention_in_days: ${{ vars.log_retention_in_days }}
          TF_VAR_log_route53_group_name: ${{ vars.log_route53_group_name }}
          TF_VAR_domain_log_policy: ${{ vars.domain_log_policy }}
        run: terraform apply -auto-approve tfplan
